[package]
name = "storm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-colors = "3.5.0"
lazy_static = "1.4.0"
string-builder = "0.2.0"
clap = { version = "4.2.7", features= ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
szu = { version = "0.1.0", path = "../szu" }
